#pragma once

#include <QApplication>
#include <QMainWindow>
#include <QHttp>
#include <QByteArray>
#include <QDebug>
#include <QUrl>
#include <QList>
#include <QImage>
#include <QPixmap>
#include <QPainter>
#include <QListWidget>
#include <QToolTip>
#include <QMouseEvent>
#include <QLabel>
#include <QMessageBox>
#include <QSlider>
#include <QThread>
#include <string>
#include "Poco/JSON/JSON.h"
#include "Poco/JSON/Parser.h"
#include "Poco/JSON/Stringifier.h"
#include "Poco/JSON/Object.h"
#include "Poco/Dynamic/Var.h"
#include "core.hpp"
#include "custom_event.h"
#include "http_req.h"
#include "navigator.h"
